package biocosmetik.data.objects;
// Generated 26-feb-2013 23:07:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CategoriaMateriaPrima generated by hbm2java
 */
@Entity
@Table(name="categoria_materia_prima"
    ,catalog="biocosmetik"
    , uniqueConstraints = @UniqueConstraint(columnNames="categoria") 
)
public class CategoriaMateriaPrima  implements java.io.Serializable {


     private Integer id;
     private String categoria;
     private Set<MateriaPrima> materiaPrimas = new HashSet<MateriaPrima>(0);

    public CategoriaMateriaPrima() {
    }

	
    public CategoriaMateriaPrima(String categoria) {
        this.categoria = categoria;
    }
    public CategoriaMateriaPrima(String categoria, Set<MateriaPrima> materiaPrimas) {
       this.categoria = categoria;
       this.materiaPrimas = materiaPrimas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="categoria", unique=true, nullable=false, length=45)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="categoriaMateriaPrima")
    public Set<MateriaPrima> getMateriaPrimas() {
        return this.materiaPrimas;
    }
    
    public void setMateriaPrimas(Set<MateriaPrima> materiaPrimas) {
        this.materiaPrimas = materiaPrimas;
    }




}


