package biocosmetik.data.objects;
// Generated 29-ene-2013 12:16:42 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clasificacion generated by hbm2java
 */
@Entity
@Table(name="clasificacion"
    ,catalog="biocosmetik"
)
public class Clasificacion  implements java.io.Serializable {


     private Integer id;
     private String clasificacion;
     private Set<Proveedores> proveedoreses = new HashSet<Proveedores>(0);

    public Clasificacion() {
    }

    public Clasificacion(String clasificacion, Set<Proveedores> proveedoreses) {
       this.clasificacion = clasificacion;
       this.proveedoreses = proveedoreses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="clasificacion", length=95)
    public String getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(String clasificacion) {
        this.clasificacion = clasificacion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="clasificacion")
    public Set<Proveedores> getProveedoreses() {
        return this.proveedoreses;
    }
    
    public void setProveedoreses(Set<Proveedores> proveedoreses) {
        this.proveedoreses = proveedoreses;
    }




}


