package biocosmetik.data.objects;
// Generated 26-ene-2013 15:51:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DatosFacturacion generated by hbm2java
 */
@Entity
@Table(name="datos_facturacion"
    ,catalog="biocosmetik"
)
public class DatosFacturacion  implements java.io.Serializable {


     private Integer id;
     private Clientes clientes;
     private Estados estados;
     private String rfc;
     private String razonSocial;
     private String domicilio;
     private String colonia;
     private String delegacion;
     private String codigoPostal;
     private Set<Pedidos> pedidoses = new HashSet<Pedidos>(0);

    public DatosFacturacion() {
    }

	
    public DatosFacturacion(Clientes clientes, Estados estados) {
        this.clientes = clientes;
        this.estados = estados;
    }
    public DatosFacturacion(Clientes clientes, Estados estados, String rfc, String razonSocial, String domicilio, String colonia, String delegacion, String codigoPostal, Set<Pedidos> pedidoses) {
       this.clientes = clientes;
       this.estados = estados;
       this.rfc = rfc;
       this.razonSocial = razonSocial;
       this.domicilio = domicilio;
       this.colonia = colonia;
       this.delegacion = delegacion;
       this.codigoPostal = codigoPostal;
       this.pedidoses = pedidoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente", nullable=false)
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="estado", nullable=false)
    public Estados getEstados() {
        return this.estados;
    }
    
    public void setEstados(Estados estados) {
        this.estados = estados;
    }
    
    @Column(name="RFC", length=13)
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    
    @Column(name="razon_social", length=90)
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    
    @Column(name="domicilio", length=65535)
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    
    @Column(name="colonia", length=90)
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    
    @Column(name="delegacion", length=90)
    public String getDelegacion() {
        return this.delegacion;
    }
    
    public void setDelegacion(String delegacion) {
        this.delegacion = delegacion;
    }
    
    @Column(name="codigo_postal", length=5)
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="datosFacturacion")
    public Set<Pedidos> getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set<Pedidos> pedidoses) {
        this.pedidoses = pedidoses;
    }




}


