package biocosmetik.data.objects;
// Generated 28-ene-2013 11:26:33 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EdicionProducto generated by hbm2java
 */
@Entity
@Table(name="edicion_producto"
    ,catalog="biocosmetik"
)
public class EdicionProducto  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private Set<Productos> productoses = new HashSet<Productos>(0);

    public EdicionProducto() {
    }

	
    public EdicionProducto(String nombre) {
        this.nombre = nombre;
    }
    public EdicionProducto(String nombre, String descripcion, Set<Productos> productoses) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.productoses = productoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="descripcion", length=90)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="edicionProducto")
    public Set<Productos> getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set<Productos> productoses) {
        this.productoses = productoses;
    }




}


