package biocosmetik.data.objects;
// Generated 28-ene-2013 11:26:33 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EspecificacionesProducto generated by hbm2java
 */
@Entity
@Table(name="especificaciones_producto"
    ,catalog="biocosmetik"
)
public class EspecificacionesProducto  implements java.io.Serializable {


     private int idProducto;
     private Productos productos;
     private int numeroAnalisis;
     private Date vigencia;
     private String color;
     private String olor;
     private String apariencia;
     private String homeginidad;
     private String pigmentos;
     private String ph;
     private String viscosidad;
     private String estabilidadCentrifuga;
     private String estabilidadTermica;
     private String aire;
     private String densidad;
     private String puntoFusion;
     private String gradoGrayLusacc;
     private String microbiologicos;
     private String cuentaTotal;
     private String ecoliColiformesT;
     private String hongosLevaduras;
     private String solubilidad;

    public EspecificacionesProducto() {
    }

	
    public EspecificacionesProducto(int idProducto, Productos productos, int numeroAnalisis) {
        this.idProducto = idProducto;
        this.productos = productos;
        this.numeroAnalisis = numeroAnalisis;
    }
    public EspecificacionesProducto(int idProducto, Productos productos, int numeroAnalisis, Date vigencia, String color, String olor, String apariencia, String homeginidad, String pigmentos, String ph, String viscosidad, String estabilidadCentrifuga, String estabilidadTermica, String aire, String densidad, String puntoFusion, String gradoGrayLusacc, String microbiologicos, String cuentaTotal, String ecoliColiformesT, String hongosLevaduras, String solubilidad) {
       this.idProducto = idProducto;
       this.productos = productos;
       this.numeroAnalisis = numeroAnalisis;
       this.vigencia = vigencia;
       this.color = color;
       this.olor = olor;
       this.apariencia = apariencia;
       this.homeginidad = homeginidad;
       this.pigmentos = pigmentos;
       this.ph = ph;
       this.viscosidad = viscosidad;
       this.estabilidadCentrifuga = estabilidadCentrifuga;
       this.estabilidadTermica = estabilidadTermica;
       this.aire = aire;
       this.densidad = densidad;
       this.puntoFusion = puntoFusion;
       this.gradoGrayLusacc = gradoGrayLusacc;
       this.microbiologicos = microbiologicos;
       this.cuentaTotal = cuentaTotal;
       this.ecoliColiformesT = ecoliColiformesT;
       this.hongosLevaduras = hongosLevaduras;
       this.solubilidad = solubilidad;
    }
   
     @Id 
    
    @Column(name="producto", unique=true, nullable=false)
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int producto) {
        this.idProducto = producto;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="producto", unique=true, nullable=false, insertable=false, updatable=false)
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    
    @Column(name="numero_analisis", nullable=false)
    public int getNumeroAnalisis() {
        return this.numeroAnalisis;
    }
    
    public void setNumeroAnalisis(int numeroAnalisis) {
        this.numeroAnalisis = numeroAnalisis;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="vigencia", length=10)
    public Date getVigencia() {
        return this.vigencia;
    }
    
    public void setVigencia(Date vigencia) {
        this.vigencia = vigencia;
    }
    
    @Column(name="color", length=80)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    
    @Column(name="olor", length=80)
    public String getOlor() {
        return this.olor;
    }
    
    public void setOlor(String olor) {
        this.olor = olor;
    }
    
    @Column(name="apariencia", length=80)
    public String getApariencia() {
        return this.apariencia;
    }
    
    public void setApariencia(String apariencia) {
        this.apariencia = apariencia;
    }
    
    @Column(name="homeginidad", length=80)
    public String getHomeginidad() {
        return this.homeginidad;
    }
    
    public void setHomeginidad(String homeginidad) {
        this.homeginidad = homeginidad;
    }
    
    @Column(name="pigmentos", length=80)
    public String getPigmentos() {
        return this.pigmentos;
    }
    
    public void setPigmentos(String pigmentos) {
        this.pigmentos = pigmentos;
    }
    
    @Column(name="ph", length=80)
    public String getPh() {
        return this.ph;
    }
    
    public void setPh(String ph) {
        this.ph = ph;
    }
    
    @Column(name="viscosidad", length=80)
    public String getViscosidad() {
        return this.viscosidad;
    }
    
    public void setViscosidad(String viscosidad) {
        this.viscosidad = viscosidad;
    }
    
    @Column(name="estabilidad_centrifuga", length=80)
    public String getEstabilidadCentrifuga() {
        return this.estabilidadCentrifuga;
    }
    
    public void setEstabilidadCentrifuga(String estabilidadCentrifuga) {
        this.estabilidadCentrifuga = estabilidadCentrifuga;
    }
    
    @Column(name="estabilidad_termica", length=80)
    public String getEstabilidadTermica() {
        return this.estabilidadTermica;
    }
    
    public void setEstabilidadTermica(String estabilidadTermica) {
        this.estabilidadTermica = estabilidadTermica;
    }
    
    @Column(name="aire", length=80)
    public String getAire() {
        return this.aire;
    }
    
    public void setAire(String aire) {
        this.aire = aire;
    }
    
    @Column(name="densidad", length=80)
    public String getDensidad() {
        return this.densidad;
    }
    
    public void setDensidad(String densidad) {
        this.densidad = densidad;
    }
    
    @Column(name="punto_fusion", length=80)
    public String getPuntoFusion() {
        return this.puntoFusion;
    }
    
    public void setPuntoFusion(String puntoFusion) {
        this.puntoFusion = puntoFusion;
    }
    
    @Column(name="grado_gray_lusacc", length=80)
    public String getGradoGrayLusacc() {
        return this.gradoGrayLusacc;
    }
    
    public void setGradoGrayLusacc(String gradoGrayLusacc) {
        this.gradoGrayLusacc = gradoGrayLusacc;
    }
    
    @Column(name="microbiologicos", length=80)
    public String getMicrobiologicos() {
        return this.microbiologicos;
    }
    
    public void setMicrobiologicos(String microbiologicos) {
        this.microbiologicos = microbiologicos;
    }
    
    @Column(name="cuenta_total", length=80)
    public String getCuentaTotal() {
        return this.cuentaTotal;
    }
    
    public void setCuentaTotal(String cuentaTotal) {
        this.cuentaTotal = cuentaTotal;
    }
    
    @Column(name="ecoli_coliformes_t", length=80)
    public String getEcoliColiformesT() {
        return this.ecoliColiformesT;
    }
    
    public void setEcoliColiformesT(String ecoliColiformesT) {
        this.ecoliColiformesT = ecoliColiformesT;
    }
    
    @Column(name="hongos_levaduras", length=80)
    public String getHongosLevaduras() {
        return this.hongosLevaduras;
    }
    
    public void setHongosLevaduras(String hongosLevaduras) {
        this.hongosLevaduras = hongosLevaduras;
    }
    
    @Column(name="solubilidad", length=80)
    public String getSolubilidad() {
        return this.solubilidad;
    }
    
    public void setSolubilidad(String solubilidad) {
        this.solubilidad = solubilidad;
    }




}


