package biocosmetik.data.objects;
// Generated 29-ene-2013 12:16:42 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estados generated by hbm2java
 */
@Entity
@Table(name="estados"
    ,catalog="biocosmetik"
)
public class Estados  implements java.io.Serializable {


     private Integer id;
     private String estado;
     private Set<Proveedores> proveedoreses = new HashSet<Proveedores>(0);

    public Estados() {
    }

    public Estados(String estado, Set<Proveedores> proveedoreses) {
       this.estado = estado;
       this.proveedoreses = proveedoreses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="estado", length=90)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estados")
    public Set<Proveedores> getProveedoreses() {
        return this.proveedoreses;
    }
    
    public void setProveedoreses(Set<Proveedores> proveedoreses) {
        this.proveedoreses = proveedoreses;
    }




}


