package biocosmetik.data.objects;
// Generated 02-mar-2013 10:02:17 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InventarioMaterialesAcondicionamiento generated by hbm2java
 */
@Entity
@Table(name = "inventario_materiales_acondicionamiento", catalog = "biocosmetik")
public class InventarioMaterialesAcondicionamiento implements java.io.Serializable {

    private Integer id;
    private MaterialesAcondicionamiento materialesAcondicionamiento;
    private StatusInventario statusInventario;
    private TipoEntradaInventario tipoEntradaInventario;
    private String lote;
    private String cantidad;

    public InventarioMaterialesAcondicionamiento() {
    }

    public InventarioMaterialesAcondicionamiento(MaterialesAcondicionamiento materialesAcondicionamiento, StatusInventario statusInventario, TipoEntradaInventario tipoEntradaInventario, String lote, String cantidad) {
        this.materialesAcondicionamiento = materialesAcondicionamiento;
        this.statusInventario = statusInventario;
        this.tipoEntradaInventario = tipoEntradaInventario;
        this.lote = lote;
        this.cantidad = cantidad;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "materiales_acondicionamiento", nullable = false)
    public MaterialesAcondicionamiento getMaterialesAcondicionamiento() {
        return this.materialesAcondicionamiento;
    }

    public void setMaterialesAcondicionamiento(MaterialesAcondicionamiento materialesAcondicionamiento) {
        this.materialesAcondicionamiento = materialesAcondicionamiento;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "status_inventario", nullable = false)
    public StatusInventario getStatusInventario() {
        return this.statusInventario;
    }

    public void setStatusInventario(StatusInventario statusInventario) {
        this.statusInventario = statusInventario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tipo_entrada_inventario", nullable = false)
    public TipoEntradaInventario getTipoEntradaInventario() {
        return this.tipoEntradaInventario;
    }

    public void setTipoEntradaInventario(TipoEntradaInventario tipoEntradaInventario) {
        this.tipoEntradaInventario = tipoEntradaInventario;
    }

    @Column(name = "lote", nullable = false, length = 45)
    public String getLote() {
        return this.lote;
    }

    public void setLote(String lote) {
        this.lote = lote;
    }

    @Column(name = "cantidad", nullable = false, length = 45)
    public String getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }
}
