package biocosmetik.data.objects;
// Generated 29-ene-2013 12:16:42 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * InventarioMateriaPrima generated by hbm2java
 */
@Entity
@Table(name="inventario_materia_prima"
    ,catalog="biocosmetik"
    , uniqueConstraints = @UniqueConstraint(columnNames="lote") 
)
public class InventarioMateriaPrima  implements java.io.Serializable {


     private Integer id;
     private StatusInventario statusInventario;
     private TipoEntradaInventario tipoEntradaInventario;
     private MateriaPrima materiaPrima;
     private String lote;
     private String cantidad;

    public InventarioMateriaPrima() {
    }

	
    public InventarioMateriaPrima(StatusInventario statusInventario, TipoEntradaInventario tipoEntradaInventario, MateriaPrima materiaPrima, String lote) {
        this.statusInventario = statusInventario;
        this.tipoEntradaInventario = tipoEntradaInventario;
        this.materiaPrima = materiaPrima;
        this.lote = lote;
    }
    public InventarioMateriaPrima(StatusInventario statusInventario, TipoEntradaInventario tipoEntradaInventario, MateriaPrima materiaPrima, String lote, String cantidad) {
       this.statusInventario = statusInventario;
       this.tipoEntradaInventario = tipoEntradaInventario;
       this.materiaPrima = materiaPrima;
       this.lote = lote;
       this.cantidad = cantidad;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status", nullable=false)
    public StatusInventario getStatusInventario() {
        return this.statusInventario;
    }
    
    public void setStatusInventario(StatusInventario statusInventario) {
        this.statusInventario = statusInventario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_entrada", nullable=false)
    public TipoEntradaInventario getTipoEntradaInventario() {
        return this.tipoEntradaInventario;
    }
    
    public void setTipoEntradaInventario(TipoEntradaInventario tipoEntradaInventario) {
        this.tipoEntradaInventario = tipoEntradaInventario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="materia_prima", nullable=false)
    public MateriaPrima getMateriaPrima() {
        return this.materiaPrima;
    }
    
    public void setMateriaPrima(MateriaPrima materiaPrima) {
        this.materiaPrima = materiaPrima;
    }
    
    @Column(name="lote", unique=true, nullable=false, length=45)
    public String getLote() {
        return this.lote;
    }
    
    public void setLote(String lote) {
        this.lote = lote;
    }
    
    @Column(name="cantidad", length=45)
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }




}


