package biocosmetik.data.objects;
// Generated 28-ene-2013 11:26:33 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LineaProductos generated by hbm2java
 */
@Entity
@Table(name="linea_productos"
    ,catalog="biocosmetik"
)
public class LineaProductos  implements java.io.Serializable {


     private Integer id;
     private Clientes clientes;
     private String nombreLinea;
     private String descripcionLinea;
     private Set<Productos> productoses = new HashSet<Productos>(0);

    public LineaProductos() {
    }

	
    public LineaProductos(Clientes clientes, String nombreLinea) {
        this.clientes = clientes;
        this.nombreLinea = nombreLinea;
    }
    public LineaProductos(Clientes clientes, String nombreLinea, String descripcionLinea, Set<Productos> productoses) {
       this.clientes = clientes;
       this.nombreLinea = nombreLinea;
       this.descripcionLinea = descripcionLinea;
       this.productoses = productoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente", nullable=false)
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    
    @Column(name="nombre_linea", nullable=false, length=45)
    public String getNombreLinea() {
        return this.nombreLinea;
    }
    
    public void setNombreLinea(String nombreLinea) {
        this.nombreLinea = nombreLinea;
    }
    
    @Column(name="descripcion_linea", length=90)
    public String getDescripcionLinea() {
        return this.descripcionLinea;
    }
    
    public void setDescripcionLinea(String descripcionLinea) {
        this.descripcionLinea = descripcionLinea;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="lineaProductos")
    public Set<Productos> getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set<Productos> productoses) {
        this.productoses = productoses;
    }




}


