package biocosmetik.data.objects;
// Generated 26-ene-2013 15:51:06 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MaterialesAcondicionamiento generated by hbm2java
 */
@Entity
@Table(name="materiales_acondicionamiento"
    ,catalog="biocosmetik"
)
public class MaterialesAcondicionamiento  implements java.io.Serializable {


     private Integer id;
     private Pertenencia pertenencia;
     private CategoriaMaterialAcondicionamiento categoriaMaterialAcondicionamiento;
     private Proveedores proveedores;
     private String nombre;
     private String clave;
     private String descripcion;
     private String claveProveedor;
     private Integer clasificacion;
     private String ubicacion;

    public MaterialesAcondicionamiento() {
    }

	
    public MaterialesAcondicionamiento(Pertenencia pertenencia, CategoriaMaterialAcondicionamiento categoriaMaterialAcondicionamiento, Proveedores proveedores) {
        this.pertenencia = pertenencia;
        this.categoriaMaterialAcondicionamiento = categoriaMaterialAcondicionamiento;
        this.proveedores = proveedores;
    }
    public MaterialesAcondicionamiento(Pertenencia pertenencia, CategoriaMaterialAcondicionamiento categoriaMaterialAcondicionamiento, Proveedores proveedores, String nombre, String clave, String descripcion, String claveProveedor, Integer clasificacion, String ubicacion) {
       this.pertenencia = pertenencia;
       this.categoriaMaterialAcondicionamiento = categoriaMaterialAcondicionamiento;
       this.proveedores = proveedores;
       this.nombre = nombre;
       this.clave = clave;
       this.descripcion = descripcion;
       this.claveProveedor = claveProveedor;
       this.clasificacion = clasificacion;
       this.ubicacion = ubicacion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pertenencia", nullable=false)
    public Pertenencia getPertenencia() {
        return this.pertenencia;
    }
    
    public void setPertenencia(Pertenencia pertenencia) {
        this.pertenencia = pertenencia;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="categoria", nullable=false)
    public CategoriaMaterialAcondicionamiento getCategoriaMaterialAcondicionamiento() {
        return this.categoriaMaterialAcondicionamiento;
    }
    
    public void setCategoriaMaterialAcondicionamiento(CategoriaMaterialAcondicionamiento categoriaMaterialAcondicionamiento) {
        this.categoriaMaterialAcondicionamiento = categoriaMaterialAcondicionamiento;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proveedor", nullable=false)
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    
    @Column(name="nombre", length=180)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="clave", length=45)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    
    @Column(name="descripcion", length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="clave_proveedor", length=45)
    public String getClaveProveedor() {
        return this.claveProveedor;
    }
    
    public void setClaveProveedor(String claveProveedor) {
        this.claveProveedor = claveProveedor;
    }
    
    @Column(name="clasificacion")
    public Integer getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(Integer clasificacion) {
        this.clasificacion = clasificacion;
    }
    
    @Column(name="ubicacion", length=100)
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }




}


