package biocosmetik.data.objects;
// Generated 26-feb-2013 23:07:31 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MateriaPrima generated by hbm2java
 */
@Entity
@Table(name = "materia_prima", catalog = "biocosmetik", uniqueConstraints =
@UniqueConstraint(columnNames = "clave"))
public class MateriaPrima implements java.io.Serializable {

    private Integer id;
    private UnidadMedida unidadMedida;
    private CategoriaMateriaPrima categoriaMateriaPrima;
    private Proveedores proveedores;
    private String clave;
    private String nombre;
    private String nombreInci;
    private String nombreGenerico;
    private String nombreCientifico;
    private String colorIndex;
    private String cas;
    private String descripcion;
    private String ubicacion;
    private Set<Sustitutos> sustitutos = new HashSet<Sustitutos>(0);
    private EspecificacionesMateriaPrima especificacionesMateriaPrimas;
    private Set<InventarioMateriaPrima> inventarioMateriaPrimas = new HashSet<InventarioMateriaPrima>(0);

    public MateriaPrima() {
    }

    public MateriaPrima(UnidadMedida unidadMedida, CategoriaMateriaPrima categoriaMateriaPrima, Proveedores proveedores, String clave) {
        this.unidadMedida = unidadMedida;
        this.categoriaMateriaPrima = categoriaMateriaPrima;
        this.proveedores = proveedores;
        this.clave = clave;
    }

    public MateriaPrima(UnidadMedida unidadMedida, CategoriaMateriaPrima categoriaMateriaPrima, Proveedores proveedores, String clave, String nombre, String nombreInci, String nombreGenerico, String nombreCientifico, String colorIndex, String cas, String descripcion, String ubicacion, Set<Sustitutos> sustitutos, EspecificacionesMateriaPrima especificacionesMateriaPrimas, Set<InventarioMateriaPrima> inventarioMateriaPrimas) {
        this.unidadMedida = unidadMedida;
        this.categoriaMateriaPrima = categoriaMateriaPrima;
        this.proveedores = proveedores;
        this.clave = clave;
        this.nombre = nombre;
        this.nombreInci = nombreInci;
        this.nombreGenerico = nombreGenerico;
        this.nombreCientifico = nombreCientifico;
        this.colorIndex = colorIndex;
        this.cas = cas;
        this.descripcion = descripcion;
        this.ubicacion = ubicacion;
        this.sustitutos = sustitutos;
        this.especificacionesMateriaPrimas = especificacionesMateriaPrimas;
        this.inventarioMateriaPrimas = inventarioMateriaPrimas;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "unidad_medida", nullable = false)
    public UnidadMedida getUnidadMedida() {
        return this.unidadMedida;
    }

    public void setUnidadMedida(UnidadMedida unidadMedida) {
        this.unidadMedida = unidadMedida;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "categoria", nullable = false)
    public CategoriaMateriaPrima getCategoriaMateriaPrima() {
        return this.categoriaMateriaPrima;
    }

    public void setCategoriaMateriaPrima(CategoriaMateriaPrima categoriaMateriaPrima) {
        this.categoriaMateriaPrima = categoriaMateriaPrima;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "proveedor", nullable = false)
    public Proveedores getProveedores() {
        return this.proveedores;
    }

    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }

    @Column(name = "clave", nullable = false, length = 15)
    public String getClave() {
        return this.clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }

    @Column(name = "nombre", length = 150)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "nombre_INCI", length = 65535)
    public String getNombreInci() {
        return this.nombreInci;
    }

    public void setNombreInci(String nombreInci) {
        this.nombreInci = nombreInci;
    }

    @Column(name = "nombre_generico", length = 150)
    public String getNombreGenerico() {
        return this.nombreGenerico;
    }

    public void setNombreGenerico(String nombreGenerico) {
        this.nombreGenerico = nombreGenerico;
    }

    @Column(name = "nombre_cientifico", length = 150)
    public String getNombreCientifico() {
        return this.nombreCientifico;
    }

    public void setNombreCientifico(String nombreCientifico) {
        this.nombreCientifico = nombreCientifico;
    }

    @Column(name = "color_index", length = 50)
    public String getColorIndex() {
        return this.colorIndex;
    }

    public void setColorIndex(String colorIndex) {
        this.colorIndex = colorIndex;
    }

    @Column(name = "CAS", length = 65535)
    public String getCas() {
        return this.cas;
    }

    public void setCas(String cas) {
        this.cas = cas;
    }

    @Column(name = "descripcion", length = 65535)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "ubicacion", length = 50)
    public String getUbicacion() {
        return this.ubicacion;
    }

    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "materiaPrimaBySustituto")
    public Set<Sustitutos> getSustitutos() {
        return this.sustitutos;
    }

    public void setSustitutos(Set<Sustitutos> sustitutos) {
        this.sustitutos = sustitutos;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "materiaPrima")
    public Set<InventarioMateriaPrima> getInventarioMateriaPrimas() {
        return this.inventarioMateriaPrimas;
    }

    public void setInventarioMateriaPrimas(Set<InventarioMateriaPrima> inventarioMateriaPrimas) {
        this.inventarioMateriaPrimas = inventarioMateriaPrimas;
    }

    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "materiaPrima")
    public EspecificacionesMateriaPrima getEspecificacionesMateriaPrimas() {
        return this.especificacionesMateriaPrimas;
    }

    public void setEspecificacionesMateriaPrimas(EspecificacionesMateriaPrima especificacionesMateriaPrimas) {
        this.especificacionesMateriaPrimas = especificacionesMateriaPrimas;
    }
}
