package biocosmetik.data.objects;
// Generated 26-ene-2013 15:51:06 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedidos generated by hbm2java
 */
@Entity
@Table(name="pedidos"
    ,catalog="biocosmetik"
)
public class Pedidos  implements java.io.Serializable {


     private Integer id;
     private Empleados empleados;
     private DatosFacturacion datosFacturacion;
     private DatosEntrega datosEntrega;
     private Clientes clientes;
     private CondicionesVenta condicionesVenta;
     private int status;
     private String folioCliente;
     private Date fechaInicioEntrega;
     private Date fechaLimiteEntrega;
     private Date fechaPedido;
     private Date fechaCaptura;
     private String instruccionesEspeciales;
     private BigDecimal importe;

    public Pedidos() {
    }

	
    public Pedidos(Empleados empleados, DatosFacturacion datosFacturacion, DatosEntrega datosEntrega, Clientes clientes, CondicionesVenta condicionesVenta, int status) {
        this.empleados = empleados;
        this.datosFacturacion = datosFacturacion;
        this.datosEntrega = datosEntrega;
        this.clientes = clientes;
        this.condicionesVenta = condicionesVenta;
        this.status = status;
    }
    public Pedidos(Empleados empleados, DatosFacturacion datosFacturacion, DatosEntrega datosEntrega, Clientes clientes, CondicionesVenta condicionesVenta, int status, String folioCliente, Date fechaInicioEntrega, Date fechaLimiteEntrega, Date fechaPedido, Date fechaCaptura, String instruccionesEspeciales, BigDecimal importe) {
       this.empleados = empleados;
       this.datosFacturacion = datosFacturacion;
       this.datosEntrega = datosEntrega;
       this.clientes = clientes;
       this.condicionesVenta = condicionesVenta;
       this.status = status;
       this.folioCliente = folioCliente;
       this.fechaInicioEntrega = fechaInicioEntrega;
       this.fechaLimiteEntrega = fechaLimiteEntrega;
       this.fechaPedido = fechaPedido;
       this.fechaCaptura = fechaCaptura;
       this.instruccionesEspeciales = instruccionesEspeciales;
       this.importe = importe;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vendedor", nullable=false)
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="datos_facturacion", nullable=false)
    public DatosFacturacion getDatosFacturacion() {
        return this.datosFacturacion;
    }
    
    public void setDatosFacturacion(DatosFacturacion datosFacturacion) {
        this.datosFacturacion = datosFacturacion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="datos_entrega", nullable=false)
    public DatosEntrega getDatosEntrega() {
        return this.datosEntrega;
    }
    
    public void setDatosEntrega(DatosEntrega datosEntrega) {
        this.datosEntrega = datosEntrega;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente", nullable=false)
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="condiciones_venta", nullable=false)
    public CondicionesVenta getCondicionesVenta() {
        return this.condicionesVenta;
    }
    
    public void setCondicionesVenta(CondicionesVenta condicionesVenta) {
        this.condicionesVenta = condicionesVenta;
    }
    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    
    @Column(name="folio_cliente", length=10)
    public String getFolioCliente() {
        return this.folioCliente;
    }
    
    public void setFolioCliente(String folioCliente) {
        this.folioCliente = folioCliente;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio_entrega", length=10)
    public Date getFechaInicioEntrega() {
        return this.fechaInicioEntrega;
    }
    
    public void setFechaInicioEntrega(Date fechaInicioEntrega) {
        this.fechaInicioEntrega = fechaInicioEntrega;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_limite_entrega", length=10)
    public Date getFechaLimiteEntrega() {
        return this.fechaLimiteEntrega;
    }
    
    public void setFechaLimiteEntrega(Date fechaLimiteEntrega) {
        this.fechaLimiteEntrega = fechaLimiteEntrega;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_pedido", length=10)
    public Date getFechaPedido() {
        return this.fechaPedido;
    }
    
    public void setFechaPedido(Date fechaPedido) {
        this.fechaPedido = fechaPedido;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_captura", length=10)
    public Date getFechaCaptura() {
        return this.fechaCaptura;
    }
    
    public void setFechaCaptura(Date fechaCaptura) {
        this.fechaCaptura = fechaCaptura;
    }
    
    @Column(name="instrucciones_especiales", length=65535)
    public String getInstruccionesEspeciales() {
        return this.instruccionesEspeciales;
    }
    
    public void setInstruccionesEspeciales(String instruccionesEspeciales) {
        this.instruccionesEspeciales = instruccionesEspeciales;
    }
    
    @Column(name="importe", precision=8)
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }




}


