package biocosmetik.data.objects;
// Generated 26-ene-2013 15:51:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pertenencia generated by hbm2java
 */
@Entity
@Table(name="pertenencia"
    ,catalog="biocosmetik"
)
public class Pertenencia  implements java.io.Serializable {


     private Integer id;
     private String dueno;
     private Set<MaterialesAcondicionamiento> materialesAcondicionamientos = new HashSet<MaterialesAcondicionamiento>(0);

    public Pertenencia() {
    }

    public Pertenencia(String dueno, Set<MaterialesAcondicionamiento> materialesAcondicionamientos) {
       this.dueno = dueno;
       this.materialesAcondicionamientos = materialesAcondicionamientos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="dueno", length=45)
    public String getDueno() {
        return this.dueno;
    }
    
    public void setDueno(String dueno) {
        this.dueno = dueno;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pertenencia")
    public Set<MaterialesAcondicionamiento> getMaterialesAcondicionamientos() {
        return this.materialesAcondicionamientos;
    }
    
    public void setMaterialesAcondicionamientos(Set<MaterialesAcondicionamiento> materialesAcondicionamientos) {
        this.materialesAcondicionamientos = materialesAcondicionamientos;
    }




}


