package biocosmetik.data.objects;
// Generated 27-feb-2013 23:08:20 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductoTerminado generated by hbm2java
 */
@Entity
@Table(name="producto_terminado"
    ,catalog="biocosmetik"
)
public class ProductoTerminado  implements java.io.Serializable {


     private Integer id;
     private String clave;
     private String nombre;
     private String descripcion;
     private String presentacion;
     private Clientes clientes;

    public ProductoTerminado() {
    }

	
    public ProductoTerminado(String clave, Clientes cliente, String nombre) {
        this.clave = clave;
        this.clientes = cliente;
        this.nombre = nombre;
    }
    public ProductoTerminado(String clave, Clientes cliente, String nombre, String descripcion, String presentacion) {
       this.clave = clave;
       this.clientes = cliente;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.presentacion = presentacion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="clave", nullable=false, length=15)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente", nullable=false)
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    
    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="descripcion", length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="presentacion", length=35)
    public String getPresentacion() {
        return this.presentacion;
    }
    
    public void setPresentacion(String presentacion) {
        this.presentacion = presentacion;
    }




}


