package biocosmetik.data.objects;
// Generated 02-mar-2013 12:15:03 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sexo generated by hbm2java
 */
@Entity
@Table(name = "sexo", catalog = "biocosmetik")
public class Sexo implements java.io.Serializable {

    private Integer id;
    private String sexo;
    private Set<Empleados> Empleados = new HashSet<Empleados>(0);

    public Sexo() {
    }

    public Sexo(String sexo) {
        this.sexo = sexo;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "sexo", length = 45)
    public String getSexo() {
        return this.sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "empleados")
    public Set<Empleados> getEmpleados() {
        return this.Empleados;
    }

    public void setEmpleados(Set<Empleados> Empleados) {
        this.Empleados = Empleados;
    }
}
