package biocosmetik.data.objects;
// Generated 29-ene-2013 12:16:42 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoEntradaInventario generated by hbm2java
 */
@Entity
@Table(name="tipo_entrada_inventario"
    ,catalog="biocosmetik"
)
public class TipoEntradaInventario  implements java.io.Serializable {


     private Integer id;
     private String tipo;
     private Set<InventarioMateriaPrima> inventarioMateriaPrimas = new HashSet<InventarioMateriaPrima>(0);

    public TipoEntradaInventario() {
    }

    public TipoEntradaInventario(String tipo, Set<InventarioMateriaPrima> inventarioMateriaPrimas) {
       this.tipo = tipo;
       this.inventarioMateriaPrimas = inventarioMateriaPrimas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="tipo", length=45)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tipoEntradaInventario")
    public Set<InventarioMateriaPrima> getInventarioMateriaPrimas() {
        return this.inventarioMateriaPrimas;
    }
    
    public void setInventarioMateriaPrimas(Set<InventarioMateriaPrima> inventarioMateriaPrimas) {
        this.inventarioMateriaPrimas = inventarioMateriaPrimas;
    }




}


