package biocosmetik.data.objects;
// Generated 28-ene-2013 11:26:33 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoProducto generated by hbm2java
 */
@Entity
@Table(name="tipo_producto"
    ,catalog="biocosmetik"
)
public class TipoProducto  implements java.io.Serializable {


     private Integer id;
     private String tipoProducto;
     private Set<Productos> productoses = new HashSet<Productos>(0);

    public TipoProducto() {
    }

	
    public TipoProducto(String tipoProducto) {
        this.tipoProducto = tipoProducto;
    }
    public TipoProducto(String tipoProducto, Set<Productos> productoses) {
       this.tipoProducto = tipoProducto;
       this.productoses = productoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="tipo_producto", nullable=false, length=45)
    public String getTipoProducto() {
        return this.tipoProducto;
    }
    
    public void setTipoProducto(String tipoProducto) {
        this.tipoProducto = tipoProducto;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tipoProducto")
    public Set<Productos> getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set<Productos> productoses) {
        this.productoses = productoses;
    }




}


