package biocosmetik.data.objects;
// Generated 26-ene-2013 15:51:06 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,catalog="biocosmetik"
    , uniqueConstraints = @UniqueConstraint(columnNames="usuario") 
)
public class Usuarios  implements java.io.Serializable {


     private Integer id;
     private TipoUsuario tipoUsuario;
     private Empleados empleados;
     private String usuario;
     private String password;
     private byte activo;

    public Usuarios() {
    }

    public Usuarios(TipoUsuario tipoUsuario, Empleados empleados, String usuario, String password, byte activo) {
       this.tipoUsuario = tipoUsuario;
       this.empleados = empleados;
       this.usuario = usuario;
       this.password = password;
       this.activo = activo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo", nullable=false)
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empleado", nullable=false)
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }
    
    @Column(name="usuario", unique=true, nullable=false, length=15)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="activo", nullable=false)
    public byte getActivo() {
        return this.activo;
    }
    
    public void setActivo(byte activo) {
        this.activo = activo;
    }




}


